language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django15
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18

install:
  - make requirements

before_script:
  - pip install python-coveralls

script:
    - tox -e $TOX_ENV

after_success:
  - coveralls
